// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"brazilian-api-quotes/repository"
	"brazilian-api-quotes/service"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitializeQuoteService(db *pgxpool.Pool) *service.QuoteService {
	quoteRepository := repository.NewQuoteRepository(db)
	quoteService := service.NewQuoteService(quoteRepository)
	return quoteService
}
